/**
 * Seed script to populate database with test events
 */

import { PrismaClient } from '@prisma/client';
import { addDays, addHours } from 'date-fns';

const prisma = new PrismaClient();

const TEST_EVENTS = [
  {
    externalId: 'test-zoo-1',
    source: 'test',
    title: 'Zoo Praha - Den dětí',
    description: 'Speciální program pro děti s krmením zvířat a interaktivními workshopy.',
    startDateTime: addDays(new Date(), 3),
    endDateTime: addHours(addDays(new Date(), 3), 4),
    locationName: 'Zoo Praha',
    address: 'U Trojského zámku 3, Praha 7',
    latitude: 50.1164,
    longitude: 14.4124,
    distanceFromPrague: 5.2,
    category: 'zoo',
    ageMin: 2,
    ageMax: 12,
    adultPrice: 200,
    childPrice: 150,
    familyPrice: 600,
    isOutdoor: true,
    durationMinutes: 240,
    imageUrl: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800',
    bookingUrl: 'https://www.zoopraha.cz',
    scoreToddler: 85,
    scoreChild: 92,
    scoreFamily: 95,
  },
  {
    externalId: 'test-techmania-1',
    source: 'test',
    title: 'Techmania Science Center',
    description: 'Interaktivní vědecké muzeum s experimenty a planetáriem.',
    startDateTime: addDays(new Date(), 5),
    locationName: 'Techmania Science Center',
    address: 'U Planetária 1, Praha 7',
    latitude: 50.0974,
    longitude: 14.4229,
    distanceFromPrague: 2.8,
    category: 'museum',
    ageMin: 5,
    ageMax: 15,
    adultPrice: 180,
    childPrice: 120,
    familyPrice: 500,
    isOutdoor: false,
    durationMinutes: 180,
    imageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800',
    bookingUrl: 'https://www.techmania.cz',
    scoreToddler: 45,
    scoreChild: 88,
    scoreFamily: 75,
  },
  {
    externalId: 'test-puppet-1',
    source: 'test',
    title: 'Loutkové divadlo - Kašpárek a princezna',
    description: 'Tradiční loutkové představení pro nejmenší děti.',
    startDateTime: addDays(new Date(), 2),
    locationName: 'Divadlo Minor',
    address: 'Vodičkova 6, Praha 1',
    latitude: 50.0807,
    longitude: 14.4249,
    distanceFromPrague: 0.8,
    category: 'theater',
    ageMin: 2,
    ageMax: 6,
    adultPrice: 120,
    childPrice: 80,
    isOutdoor: false,
    durationMinutes: 45,
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    bookingUrl: 'https://www.minor.cz',
    scoreToddler: 92,
    scoreChild: 60,
    scoreFamily: 78,
  },
  {
    externalId: 'test-aquapalace-1',
    source: 'test',
    title: 'Aquapalace Praha',
    description: 'Největší aquapark ve střední Evropě s tobogány a bazény.',
    startDateTime: addDays(new Date(), 7),
    locationName: 'Aquapalace Praha',
    address: 'Pražská 138, Čestlice',
    latitude: 50.0158,
    longitude: 14.5562,
    distanceFromPrague: 12.5,
    category: 'sport',
    ageMin: 1,
    ageMax: 99,
    adultPrice: 450,
    childPrice: 350,
    familyPrice: 1200,
    isOutdoor: false,
    durationMinutes: 240,
    imageUrl: 'https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?w=800',
    bookingUrl: 'https://www.aquapalace.cz',
    scoreToddler: 75,
    scoreChild: 90,
    scoreFamily: 88,
  },
  {
    externalId: 'test-planetarium-1',
    source: 'test',
    title: 'Planetárium Praha - Vesmír pro děti',
    description: 'Speciální program o vesmíru přizpůsobený dětem.',
    startDateTime: addDays(new Date(), 4),
    locationName: 'Planetárium Praha',
    address: 'Královská obora 233, Praha 7',
    latitude: 50.0997,
    longitude: 14.4308,
    distanceFromPrague: 2.5,
    category: 'educational',
    ageMin: 6,
    ageMax: 14,
    adultPrice: 150,
    childPrice: 100,
    isOutdoor: false,
    durationMinutes: 60,
    imageUrl: 'https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=800',
    bookingUrl: 'https://www.planetarium.cz',
    scoreToddler: 40,
    scoreChild: 87,
    scoreFamily: 72,
  },
  {
    externalId: 'test-playground-1',
    source: 'test',
    title: 'Funpark Čestlice - Zdarma',
    description: 'Moderní venkovní hřiště s prolézačkami a pískovištěm zdarma.',
    startDateTime: addDays(new Date(), 1),
    locationName: 'Funpark Čestlice',
    address: 'Průmyslová 1, Čestlice',
    latitude: 50.0165,
    longitude: 14.5446,
    distanceFromPrague: 12.0,
    category: 'playground',
    ageMin: 1,
    ageMax: 8,
    adultPrice: 0,
    childPrice: 0,
    isOutdoor: true,
    durationMinutes: 120,
    imageUrl: 'https://images.unsplash.com/photo-1587647653615-eef25adb4d88?w=800',
    scoreToddler: 88,
    scoreChild: 70,
    scoreFamily: 82,
  },
  {
    externalId: 'test-farm-1',
    source: 'test',
    title: 'Farma Blaník - Návštěva statku',
    description: 'Poznávání zvířátek na farmě, možnost krmení.',
    startDateTime: addDays(new Date(), 6),
    locationName: 'Farma Blaník',
    address: 'Louňovice pod Blaníkem',
    latitude: 49.7847,
    longitude: 14.8174,
    distanceFromPrague: 62.0,
    category: 'outdoor',
    ageMin: 2,
    ageMax: 10,
    adultPrice: 100,
    childPrice: 50,
    isOutdoor: true,
    durationMinutes: 180,
    imageUrl: 'https://images.unsplash.com/photo-1500595046743-cd271d694d30?w=800',
    bookingUrl: 'https://example.com',
    scoreToddler: 83,
    scoreChild: 78,
    scoreFamily: 85,
  },
  {
    externalId: 'test-workshop-1',
    source: 'test',
    title: 'Kreativní dílna - Malování na keramiku',
    description: 'Workshop malování na keramiku pro děti s rodiči.',
    startDateTime: addDays(new Date(), 8),
    locationName: 'Kreativní centrum Praha',
    address: 'Národní 28, Praha 1',
    latitude: 50.0813,
    longitude: 14.4185,
    distanceFromPrague: 0.6,
    category: 'workshop',
    ageMin: 5,
    ageMax: 12,
    adultPrice: 200,
    childPrice: 200,
    isOutdoor: false,
    durationMinutes: 90,
    imageUrl: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=800',
    scoreToddler: 55,
    scoreChild: 85,
    scoreFamily: 80,
  },
];

async function main() {
  console.log('Seeding database with test events...');

  for (const event of TEST_EVENTS) {
    await prisma.event.upsert({
      where: { externalId: event.externalId },
      update: event,
      create: event,
    });
    console.log(`✓ Created event: ${event.title}`);
  }

  console.log(`\n✅ Successfully seeded ${TEST_EVENTS.length} test events!`);
  console.log('\nYou can now see them at:');
  console.log('- Toddler view: http://localhost:3000/dashboard/toddler');
  console.log('- Child view: http://localhost:3000/dashboard/child');
  console.log('- Family view: http://localhost:3000/dashboard/family');
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
